# Inventory Analysis

## Overview

...

## Imports

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

## 1. Import Data

### 1a. Define data paths

Use the imported Path function to create relative paths to data files.

In [2]:
DATA_FOLDER_PATH = Path("../data")
DATA_1_PATH = DATA_FOLDER_PATH / "diapers.csv"
DATA_2_PATH = DATA_FOLDER_PATH / "form.csv"
DATA_3_PATH = DATA_FOLDER_PATH / "form_2_new.csv"
OUTPUT_DATA_PATH = DATA_FOLDER_PATH / "output/diapers_final.csv"

### 1b. Import data from CSV files

Use pandas to load csv files as DataFrames.

In [3]:
df1 = pd.read_csv(DATA_1_PATH)
df2 = pd.read_csv(DATA_2_PATH, header=1)
df3 = pd.read_csv(DATA_3_PATH)

## 2. Data Cleaning

Because the Google Form used for data collection changed a few times, there are 3 different csv files with varying columns that need to be combined into one csv file.

The output csv file should have the following columns:  
- timestamp (date)
- branch (string)
- zip (string)
- size (string)
- packs (int)

### 2a. File 1 - diapers.csv

Display summary information.

In [4]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 59425 entries, 0 to 59424
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Timestamp  55946 non-null  str
 1   BRANCH     55930 non-null  str
 2   ZIP CODE   55938 non-null  str
 3   SIZE       52387 non-null  str
 4   # PACKS    55793 non-null  float64
 5   SIZE.1     8397 non-null   str
 6   # PACKS.1  9265 non-null   float64
 7   SIZE.2     1785 non-null   str
 8   # PACKS.2  2873 non-null   float64
 9   TOTAL      59425 non-null  int64
 10  DATE       59425 non-null  str
 11  MONTH      55946 non-null  str
 12  YEAR       55946 non-null  str
 13  DAY        55946 non-null  str
 14  WEEKDAY    55946 non-null  str
dtypes: float64(3), int64(1), str(11)
memory usage: 6.8 MB

Select required columns.

In [5]:
df1_filtered: pd.DataFrame = df1.iloc[:, 0:9]
df1_filtered.head()

,Timestamp,BRANCH,ZIP CODE,SIZE,# PACKS,SIZE.1,# PACKS.1,SIZE.2,# PACKS.2
0,9/7/2021 0:00:00,GG,63011,1,3.0,NaN,NaN,NaN,NaN
1,9/7/2021 0:00:00,GG,63011,3T,2.0,NaN,NaN,NaN,NaN
2,9/14/2021 0:00:00,GG,63118,5,2.0,NaN,NaN,NaN,NaN
3,9/14/2021 0:00:00,GG,63118,6,2.0,NaN,NaN,NaN,NaN
4,9/14/2021 0:00:00,GG,63125,5,2.0,NaN,NaN,NaN,NaN

Stack rows.

In [6]:
def stack_rows(df_filtered: pd.DataFrame) -> list[list]:
    df_list = df_filtered.values.tolist()
    combined_data = []
    for record in df_list:
        for i in range(3, 9, 2):
            if record[i] != record[i] and record[i+1] != record[i+1]:
                continue
            row = [*record[0:3], *record[i:i+2]]
            combined_data.append(row)
    return combined_data

In [7]:
combined_data_1: list[list] = stack_rows(df1_filtered)

Create DataFrame.

In [8]:
def create_df(combined_data: list[list]) -> pd.DataFrame:
    columns: list = ["timestamp", "branch", "zip", "size", "packs"]
    df_final: pd.DataFrame = pd.DataFrame(combined_data, columns=columns)
    return df_final

In [9]:
df1_final: pd.DataFrame = create_df(combined_data_1)
df1_final.head()

           timestamp branch    zip size  packs
0   9/7/2021 0:00:00     GG  63011    1    3.0
1   9/7/2021 0:00:00     GG  63011   3T    2.0
2  9/14/2021 0:00:00     GG  63118    5    2.0
3  9/14/2021 0:00:00     GG  63118    6    2.0
4  9/14/2021 0:00:00     GG  63125    5    2.0

### 2b. File 2 - form.csv

Display summary information.

In [10]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 24514 entries, 0 to 24513
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Timestamp                                 24514 non-null  str
 1   BRANCH                                    24514 non-null  str
 2   ZIP CODE                                  24514 non-null  str
 3   What are you submitting stats for?        24514 non-null  str
 4   Size                                      19367 non-null  str
 5   Unnamed: 5                                19367 non-null  str
 6   Number of PACKS OF DIAPERS distributed    19367 non-null  float64
 7   Size.1                                    7267 non-null   str
 8   Unnamed: 8                                7267 non-null   str
 9   Number of PACKS OF DIAPERS distributed.1  7129 non-null   float64
 10  Size.2                                    1563 non-null   str
 11  Unnamed: 11                               1563 non-null   str
 12  Number of PACKS OF DIAPERS distributed.2  2328 non-null   float64
 13  Number of FLOW KITS distributed           4996 non-null   float64
 14  Number of REUSABLE FLOW KITS distributed  183 non-null    float64
dtypes: float64(5), str(10)
memory usage: 2.8 MB

In [11]:
df2.head(10)

,Timestamp,BRANCH,ZIP CODE,What are you submitting stats for?,Size,Unnamed: 5,Number of PACKS OF DIAPERS distributed,Size.1,Unnamed: 8,Number of PACKS OF DIAPERS distributed.1,Size.2,Unnamed: 11,Number of PACKS OF DIAPERS distributed.2,Number of FLOW KITS distributed,Number of REUSABLE FLOW KITS distributed
0,0/0/0000 00:00:00,----,-----,Flow Kits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1,0/0/0000 00:00:00,----,-----,Resuable Flow Kits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,0/0/0000 00:00:00,----,-----,Diapers,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/2/2024 9:29:02,LC,63137,Diapers,5,5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/2/2024 9:29:19,LC,63137,Resuable Flow Kits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
5,1/2/2024 9:38:49,LC,63136,Diapers,3,3,1.0,4,4,1.0,NaN,NaN,NaN,NaN,NaN
6,1/2/2024 9:48:33,WR,63123,Diapers,4T,4T,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1/2/2024 10:00:31,LC,62040,Diapers,4,4,1.0,4,4,1.0,NaN,NaN,NaN,NaN,NaN
8,1/2/2024 10:01:09,LC,62040,Resuable Flow Kits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9,1/2/2024 10:50:17,GG,63125,Diapers,2,2,1.0,2,2,1.0,3,3,1.0,NaN,NaN

Filter to select diaper stats only.

In [12]:
df2_diapers = df2[df2.iloc[:, 3] == "Diapers"]
df2_diapers.head()

,Timestamp,BRANCH,ZIP CODE,What are you submitting stats for?,Size,Unnamed: 5,Number of PACKS OF DIAPERS distributed,Size.1,Unnamed: 8,Number of PACKS OF DIAPERS distributed.1,Size.2,Unnamed: 11,Number of PACKS OF DIAPERS distributed.2,Number of FLOW KITS distributed,Number of REUSABLE FLOW KITS distributed
2,0/0/0000 00:00:00,----,-----,Diapers,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/2/2024 9:29:02,LC,63137,Diapers,5,5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1/2/2024 9:38:49,LC,63136,Diapers,3,3,1.0,4,4,1.0,NaN,NaN,NaN,NaN,NaN
6,1/2/2024 9:48:33,WR,63123,Diapers,4T,4T,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1/2/2024 10:00:31,LC,62040,Diapers,4,4,1.0,4,4,1.0,NaN,NaN,NaN,NaN,NaN

Select required columns.

In [13]:
df2_col_idx = [0,1,2,4,6,7,9,10,12]
df2_filtered = df2_diapers.iloc[1:,df2_col_idx]
df2_filtered.head()

,Timestamp,BRANCH,ZIP CODE,Size,Number of PACKS OF DIAPERS distributed,Size.1,Number of PACKS OF DIAPERS distributed.1,Size.2,Number of PACKS OF DIAPERS distributed.2
3,1/2/2024 9:29:02,LC,63137,5,1.0,NaN,NaN,NaN,NaN
5,1/2/2024 9:38:49,LC,63136,3,1.0,4,1.0,NaN,NaN
6,1/2/2024 9:48:33,WR,63123,4T,1.0,NaN,NaN,NaN,NaN
7,1/2/2024 10:00:31,LC,62040,4,1.0,4,1.0,NaN,NaN
9,1/2/2024 10:50:17,GG,63125,2,1.0,2,1.0,3,1.0

Stack rows.

In [14]:
combined_data_2: list[list] = stack_rows(df2_filtered)

Create DataFrame.

In [15]:
df2_final = create_df(combined_data_2)
df2_final.head()

           timestamp branch    zip size  packs
0   1/2/2024 9:29:02     LC  63137    5    1.0
1   1/2/2024 9:38:49     LC  63136    3    1.0
2   1/2/2024 9:38:49     LC  63136    4    1.0
3   1/2/2024 9:48:33     WR  63123   4T    1.0
4  1/2/2024 10:00:31     LC  62040    4    1.0

### 2c. File 3 - form2.csv

Display summary information.

In [16]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 8853 entries, 0 to 8852
Data columns (total 13 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   Timestamp                                                        8853 non-null   str
 1   BRANCH                                                           8827 non-null   str
 2   ZIP CODE                                                         8853 non-null   str
 3   Size                                                             7490 non-null   str
 4   Number of PACKS OF DIAPERS distributed                           7276 non-null   float64
 5   Size.1                                                           2208 non-null   str
 6   Number of PACKS OF DIAPERS distributed.1                         2144 non-null   float64
 7   Size.2                                                           436 non-null    str
 8   Number of PACKS OF DIAPERS distributed.2                         546 non-null    float64
 9   Number of FLOW KITS distributed                                  2730 non-null   float64
 10  Number of REUSABLE FLOW KITS distributed                         180 non-null    float64
 11  Do you want to record distribution statistics?                   2370 non-null   str
 12  Are you submitting statistics or enrolling a new diaper patron?  8853 non-null   str
dtypes: float64(5), str(8)
memory usage: 899.3 KB

In [17]:
df3.head()

,Timestamp,BRANCH,ZIP CODE,Size,Number of PACKS OF DIAPERS distributed,Size.1,Number of PACKS OF DIAPERS distributed.1,Size.2,Number of PACKS OF DIAPERS distributed.2,Number of FLOW KITS distributed,Number of REUSABLE FLOW KITS distributed,Do you want to record distribution statistics?,Are you submitting statistics or enrolling a new diaper patron?
0,9/9/2023 8:55:18,FV,12345,0,0.0,0,0.0,0,0.0,0.0,0.0,NaN,Diaper Distribution
1,10/17/2025 8:54:37,PV,63114,4,1.0,6,1.0,NaN,NaN,NaN,NaN,NaN,Statistics (Diapers + Flow Kits)
2,10/17/2025 8:59:27,FV,63137,5,2.0,4,1.0,NaN,NaN,1.0,NaN,NaN,Statistics (Diapers + Flow Kits)
3,10/17/2025 9:00:27,WR,63125,5,1.0,6,1.0,NaN,NaN,1.0,NaN,NaN,Statistics (Diapers + Flow Kits)
4,10/17/2025 9:00:27,FV,63031,3,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Statistics (Diapers + Flow Kits)

Select required columns.

In [18]:
df3_filtered = df3.iloc[1:, 0:9]
df3_filtered.head()

,Timestamp,BRANCH,ZIP CODE,Size,Number of PACKS OF DIAPERS distributed,Size.1,Number of PACKS OF DIAPERS distributed.1,Size.2,Number of PACKS OF DIAPERS distributed.2
1,10/17/2025 8:54:37,PV,63114,4,1.0,6,1.0,NaN,NaN
2,10/17/2025 8:59:27,FV,63137,5,2.0,4,1.0,NaN,NaN
3,10/17/2025 9:00:27,WR,63125,5,1.0,6,1.0,NaN,NaN
4,10/17/2025 9:00:27,FV,63031,3,1.0,NaN,NaN,NaN,NaN
5,10/17/2025 9:04:45,GG,63021,5,2.0,NaN,NaN,NaN,NaN

Stack rows.

In [19]:
combined_data_3: list[list] = stack_rows(df3_filtered)

Create DataFrame.

In [20]:
df3_final = create_df(combined_data_3)
df3_final.head()

            timestamp branch    zip size  packs
0  10/17/2025 8:54:37     PV  63114    4    1.0
1  10/17/2025 8:54:37     PV  63114    6    1.0
2  10/17/2025 8:59:27     FV  63137    5    2.0
3  10/17/2025 8:59:27     FV  63137    4    1.0
4  10/17/2025 9:00:27     WR  63125    5    1.0

### 2d. Combining DataFrames into One

Concatenating all three DataFrames.

In [21]:
df_combined = pd.concat([df1_final, df2_final, df3_final], axis=0, ignore_index=True)
df_combined.head()

           timestamp branch    zip size  packs
0   9/7/2021 0:00:00     GG  63011    1    3.0
1   9/7/2021 0:00:00     GG  63011   3T    2.0
2  9/14/2021 0:00:00     GG  63118    5    2.0
3  9/14/2021 0:00:00     GG  63118    6    2.0
4  9/14/2021 0:00:00     GG  63125    5    2.0

### 2e. Handling Missing Data

Display counts of na values.

In [22]:
df_combined.isna().sum()

timestamp       1
branch         41
zip            10
size         6647
packs         825
dtype: int64

#### I. timestamp

Find missing row in timestamp column.

In [23]:
df_combined[df_combined["timestamp"].isna()]

      timestamp branch  zip size  packs
29164       NaN   ----  NaN    0    0.0

Drop row with na timestamp.

In [24]:
df_combined.drop([29164], inplace=True)

#### II. branch

Find rows with missing branch.

In [25]:
df_combined[df_combined["branch"].isna()].head()

                timestamp branch    zip size  packs
59607  5/28/2026 10:41:26    NaN  63136    2    1.0
59642  5/27/2026 10:11:53    NaN  63133    6    1.0
59933   5/19/2026 8:04:41    NaN  63122  NaN    1.0
60069  5/14/2026 11:02:06    NaN  63031    5    1.0
60663    5/4/2026 8:58:41    NaN  63033    6    1.0

Select rows without missing branch.

In [26]:
df_combined = df_combined[~df_combined["branch"].isna()]

#### III. size

Get unique sizes.

In [42]:
...

Ellipsis

I plan to use ratios to guess missing sizes aggregated over longer time periods. I will leave rows with missing sizes alone for now.

In [27]:
df_combined[df_combined["size"].isna()].head()

               timestamp branch    zip size  packs
35874  6/3/2024 13:19:25     WR  63125  NaN    2.0
35883  6/3/2024 14:21:15     WR  63118  NaN    1.0
35917   6/4/2024 9:32:43     WR  63123  NaN    2.0
35943  6/4/2024 12:18:09     WR  63125  NaN    1.0
35982  6/4/2024 15:26:56     GG  63021  NaN    1.0

#### IV. packs

In [28]:
df_combined[df_combined["packs"] > 1]

                timestamp branch    zip size  packs
0        9/7/2021 0:00:00     GG  63011    1    3.0
1        9/7/2021 0:00:00     GG  63011   3T    2.0
2       9/14/2021 0:00:00     GG  63118    5    2.0
3       9/14/2021 0:00:00     GG  63118    6    2.0
4       9/14/2021 0:00:00     GG  63125    5    2.0
...                   ...    ...    ...  ...    ...
107464   7/2/2026 8:59:44     LC  63136    3    5.0
107471  7/2/2026 10:23:58     LC  63137    4    2.0
107482  7/2/2026 12:18:42     FV  63138   3T    3.0
107502  7/2/2026 16:06:56     GG  63021    6    2.0
107510   7/3/2026 8:24:22     LC  63137    6    2.0

[16026 rows x 5 columns]

In [29]:
df_combined["timestamp"] = pd.to_datetime(df_combined["timestamp"], errors='coerce')

In [30]:
df_combined['year'] = df_combined['timestamp'].dt.year
df_combined['month'] = df_combined['timestamp'].dt.month

Pivot table of count of packs by month/year

From the following pivot, we can see that the diaper bank likely started giving out 1 pack of diapers per child instead of at most 2 in September 2022.

In [31]:
pd.set_option('display.max_rows', None)

In [32]:
prepare_for_pivot = df_combined[["packs", "year", "month"]]

I'll go ahead and just use data from January 2023 forwards. Using data from when 2 packs were given out per child could skew analytics and predictive modeling. I could try normalizing it to the current policy (dividing packs given out previous to Sept. 2022 by 2), but this assumes that distribution trends are the same before and after the policy change. Also, 2 were not always given out per child. Sometimes 1 pack was given, sometimes 3 packs were given for 2 childen, etc. It would likely be a messy conversion. 3+ years of data from after the policy change is enough for analytics model building purposes.

Also, the data is incomplete for July 2026, so I'll have the data set end after June 2026.

In [33]:
df_sorted = df_combined[(df_combined["timestamp"] >= "1/1/2023") & (df_combined["timestamp"] < "7/1/2026")].sort_values(by=["timestamp"])

In [34]:
df_sorted.head()

       timestamp branch    zip size  packs    year  month
25869 2023-01-03     WR  63123    3    1.0  2023.0    1.0
14937 2023-01-03     LC  63136    5    1.0  2023.0    1.0
14936 2023-01-03     LC  63136    4    1.0  2023.0    1.0
14935 2023-01-03     LC  63136    1    1.0  2023.0    1.0
14934 2023-01-03     LC  63136    1    1.0  2023.0    1.0

In [35]:
df_sorted.tail()

                 timestamp branch    zip size  packs    year  month
107345 2026-06-30 18:39:56     WR  63111    4    1.0  2026.0    6.0
107347 2026-06-30 18:40:03     WR  63123    5    1.0  2026.0    6.0
58301  2026-06-30 18:40:03     WR  63123    5    1.0  2026.0    6.0
58300  2026-06-30 18:53:32     FV  63031    5    NaN  2026.0    6.0
107348 2026-06-30 18:53:32     FV  63031    5    NaN  2026.0    6.0

### 2f. Filtering to target branch

Filtering to WR branch.

In [36]:
df_filtered_wr = df_sorted[df_sorted["branch"] == "WR"]
df_filtered_wr.head()

       timestamp branch    zip size  packs    year  month
25869 2023-01-03     WR  63123    3    1.0  2023.0    1.0
25893 2023-01-03     WR  63125   3t    1.0  2023.0    1.0
25892 2023-01-03     WR  63123    4    1.0  2023.0    1.0
25891 2023-01-03     WR  63129    4    1.0  2023.0    1.0
25890 2023-01-03     WR  63123    4    1.0  2023.0    1.0

### 2g. Cleaning up DataFrame

Reset index at the end.

In [37]:
df_filtered_wr.reset_index(inplace=True, drop=True)

Set df_filtered_wr to wr for easy reference.

In [38]:
wr = df_filtered_wr

## 3. Exploratory Analysis

In [39]:
wr.head()

   timestamp branch    zip size  packs    year  month
0 2023-01-03     WR  63123    3    1.0  2023.0    1.0
1 2023-01-03     WR  63125   3t    1.0  2023.0    1.0
2 2023-01-03     WR  63123    4    1.0  2023.0    1.0
3 2023-01-03     WR  63129    4    1.0  2023.0    1.0
4 2023-01-03     WR  63123    4    1.0  2023.0    1.0

In [40]:
wr.tail()

                timestamp branch    zip size  packs    year  month
19081 2026-06-30 18:39:56     WR  63111    4    1.0  2026.0    6.0
19082 2026-06-30 18:39:56     WR  63111    4    1.0  2026.0    6.0
19083 2026-06-30 18:39:56     WR  63111    4    1.0  2026.0    6.0
19084 2026-06-30 18:40:03     WR  63123    5    1.0  2026.0    6.0
19085 2026-06-30 18:40:03     WR  63123    5    1.0  2026.0    6.0

### 3a. Diaper Size Analysis

Size totals by month.

In [41]:
pd.pivot_table(wr, values='packs', index=['year', 'month'], columns=['size'], aggfunc="sum")

size             1     2    2T   2t      3    3T    3t      4    4T   4t  \
year   month
2023.0 1.0     8.0  17.0   NaN  5.0   36.0   NaN   2.0   61.0   NaN  1.0
       2.0     6.0  11.0   NaN  5.0   24.0   NaN   4.0   43.0   NaN  NaN
       3.0    11.0  15.0   NaN  5.0   42.0   NaN   2.0   48.0   NaN  5.0
       4.0     9.0  13.0   NaN  5.0   33.0   NaN   6.0   35.0   NaN  NaN
       5.0    12.0  11.0   NaN  2.0   31.0   NaN  12.0   54.0   NaN  NaN
       6.0     6.0  13.0   NaN  8.0   24.0   NaN  14.0   69.0   NaN  NaN
       7.0    14.0  16.0   NaN  8.0   45.0   NaN  13.0   46.0   NaN  NaN
       8.0    17.0  13.0   NaN  4.0   43.0   NaN  16.0   68.0   NaN  NaN
       9.0    14.0  13.0   NaN  5.0   46.0   NaN  12.0   66.0   NaN  1.0
       10.0   13.0  17.0   NaN  3.0   45.0   NaN   9.0   70.0   NaN  NaN
       11.0   16.0  16.0   1.0  1.0   39.0   3.0   3.0   81.0   NaN  3.0
       12.0   13.0  13.0   1.0  NaN   39.0   1.0   2.0   63.0   1.0  3.0
2024.0 1.0    28.0  24.0   8.0  NaN   64.0  14.0   NaN  128.0  18.0  NaN
       2.0    28.0  36.0   4.0  NaN   66.0  10.0   NaN  154.0   6.0  NaN
       3.0    20.0  22.0   8.0  NaN   58.0  14.0   NaN  138.0   8.0  NaN
       4.0    24.0  36.0  12.0  NaN   76.0  16.0   NaN  124.0  12.0  NaN
       5.0    20.0  14.0   8.0  NaN   62.0   8.0   NaN  132.0  20.0  NaN
       6.0    22.0  22.0  12.0  NaN   64.0  20.0   NaN  126.0  12.0  NaN
       7.0    36.0  22.0  14.0  NaN   52.0  10.0   NaN  130.0   8.0  NaN
       8.0    20.0  24.0  18.0  NaN  100.0  18.0   NaN  132.0  20.0  NaN
       9.0    16.0  12.0  16.0  NaN   64.0  20.0   NaN   80.0  18.0  NaN
       10.0   18.0  22.0  12.0  NaN   40.0  18.0   NaN   64.0  26.0  NaN
       11.0   20.0  16.0  12.0  NaN   52.0   8.0   NaN   44.0  18.0  NaN
       12.0   26.0  18.0  16.0  NaN   32.0  20.0   NaN   82.0  20.0  NaN
2025.0 1.0    12.0  20.0  18.0  NaN   42.0  20.0   NaN   98.0  20.0  NaN
       2.0    12.0  18.0   6.0  NaN   38.0  10.0   NaN   88.0  16.0  NaN
       3.0    18.0  16.0   2.0  NaN   52.0   8.0   NaN   58.0  18.0  NaN
       4.0    10.0  16.0   8.0  NaN   48.0   8.0   NaN   84.0  20.0  NaN
       5.0    20.0  28.0   4.0  NaN   32.0  22.0   NaN   58.0  10.0  NaN
       6.0    18.0  16.0   8.0  NaN   44.0  14.0   NaN   64.0  22.0  NaN
       7.0    36.0  30.0   6.0  NaN   40.0  20.0   NaN   48.0  22.0  NaN
       8.0    30.0  24.0   8.0  NaN   44.0  16.0   NaN   64.0  26.0  NaN
       9.0    16.0  28.0   8.0  NaN   48.0  26.0   NaN   92.0  34.0  NaN
       10.0   27.0  27.0  12.0  NaN   44.0  24.0   NaN   61.0  21.0  NaN
       11.0    6.0  10.0   4.0  NaN   23.0  11.0   NaN   29.0   9.0  NaN
       12.0    8.0  14.0   4.0  NaN   23.0  11.0   NaN   43.0  12.0  NaN
2026.0 1.0     7.0   6.0   7.0  NaN   31.0   7.0   NaN   47.0   6.0  NaN
       2.0     7.0  18.0   8.0  NaN   40.0  13.0   NaN   98.0  13.0  NaN
       3.0    14.0  18.0   8.0  NaN   62.0   9.0   NaN  110.0   8.0  NaN
       4.0    16.0  12.0  17.0  NaN   70.0   8.0   NaN   84.0   9.0  NaN
       5.0    22.0  30.0  12.0  NaN   42.0   7.0   NaN  116.0   6.0  NaN
       6.0    26.0  22.0   9.0  NaN   54.0   8.0   NaN  116.0  13.0  NaN

size              5      6    7     N    P  adult    n
year   month
2023.0 1.0     66.0  100.0  NaN   3.0  NaN    1.0  NaN
       2.0     79.0   79.0  NaN   4.0  NaN    NaN  NaN
       3.0     61.0   92.0  NaN   6.0  NaN    NaN  NaN
       4.0     66.0   83.0  NaN   8.0  NaN    NaN  NaN
       5.0     58.0  108.0  NaN  11.0  NaN    NaN  NaN
       6.0     53.0   84.0  NaN   6.0  NaN    NaN  NaN
       7.0     66.0  104.0  NaN   8.0  NaN    NaN  NaN
       8.0     72.0  119.0  NaN   5.0  NaN    NaN  NaN
       9.0     62.0  106.0  NaN   6.0  NaN    NaN  NaN
       10.0    60.0  105.0  NaN   3.0  NaN    NaN  NaN
       11.0    59.0  100.0  NaN   6.0  NaN    NaN  NaN
       12.0    89.0   86.0  NaN   3.0  NaN    NaN  1.0
2024.0 1.0    168.0  146.0  NaN   2.0  NaN    NaN  NaN
       2.0    122.0  174.0  NaN   6.0  NaN    NaN  NaN
       3.0    108.0  206.0  NaN  22.0  NaN    NaN  NaN
       4.0     98.0  166.0  NaN   8.0  NaN    NaN  NaN
       5.0    158.0  188.0  NaN   6.0  NaN    NaN  NaN
       6.0    144.0  200.0  NaN   4.0  NaN    NaN  NaN
       7.0    114.0  216.0  NaN  14.0  NaN    NaN  NaN
       8.0    174.0  180.0  NaN   6.0  NaN    NaN  NaN
       9.0    152.0  234.0  NaN   6.0  NaN    NaN  NaN
       10.0   152.0  192.0  NaN   6.0  NaN    NaN  NaN
       11.0   130.0  168.0  NaN  10.0  NaN    NaN  NaN
       12.0   204.0  100.0  NaN   6.0  NaN    NaN  NaN
2025.0 1.0     68.0  194.0  NaN  10.0  NaN    NaN  NaN
       2.0    112.0  160.0  NaN  16.0  NaN    NaN  NaN
       3.0    120.0  172.0  NaN   8.0  NaN    NaN  NaN
       4.0    106.0  222.0  NaN  10.0  NaN    NaN  NaN
       5.0    128.0  222.0  NaN   4.0  NaN    NaN  NaN
       6.0    140.0  176.0  NaN  12.0  NaN    NaN  NaN
       7.0    150.0  184.0  NaN  14.0  NaN    NaN  NaN
       8.0    118.0  228.0  NaN  12.0  NaN    NaN  NaN
       9.0    136.0  170.0  NaN  10.0  NaN    NaN  NaN
       10.0   106.0  169.0  1.0   5.0  NaN    NaN  NaN
       11.0    42.0   95.0  NaN   5.0  NaN    NaN  NaN
       12.0    55.0   88.0  NaN   2.0  NaN    NaN  NaN
2026.0 1.0     61.0   80.0  NaN   8.0  NaN    NaN  NaN
       2.0     90.0  158.0  NaN   9.0  NaN    NaN  NaN
       3.0     76.0  186.0  NaN   6.0  1.0    NaN  NaN
       4.0    106.0  186.0  NaN  10.0  NaN    NaN  NaN
       5.0     90.0  166.0  NaN   6.0  NaN    NaN  NaN
       6.0    108.0  202.0  NaN   3.0  NaN    NaN  NaN

Main Idea: Test if size ratios are consistent with Chi-Square

### 3b. Diaper Totals Analysis

Main idea: I suspect seasonality. Graph each month for each year on the same graph.

## 4. Predictive Modeling

### 4a. Estimating Diaper Totals

Main idea: Since there is a seasonal trand, use Holt-Winters Exponential Smoothing to predict totals.

### 4b. Estimating Diaper Size Totals

Main idea: number of size N diapers distributed in a month = size N proportion * estimated monthly total

## 5. Evaluating Models

### 5a. Diaper Totals Predictions

Main idea: Find the error in the model's predictions. Compare to 2026 data so far, or maybe validate on 2025 data.

### 5b. Diaper Size Totals Predictions

Main idea: Find the error in the model's predictions. Compare to 2026 data so far, or maybe validate on 2025 data.

## 6. Conclusions

Answer the following questions:
- What did I find out in exploratory analysis?
- How well did the models predict the test set?