# Inventory Analysis

## Overview

...

## Imports

In [59]:
import numpy as np
import pandas as pd
from pathlib import Path

## 1. Import Data

### 1a. Define data paths

Use the imported Path function to create relative paths to data files.

In [60]:
DATA_FOLDER_PATH = Path("../data")
DATA_1_PATH = DATA_FOLDER_PATH / "diapers.csv"
DATA_2_PATH = DATA_FOLDER_PATH / "form.csv"
DATA_3_PATH = DATA_FOLDER_PATH / "form_2_new.csv"
OUTPUT_DATA_PATH = DATA_FOLDER_PATH / "output/diapers_final.csv"

### 1b. Import data from CSV files

Use pandas to load csv files as DataFrames.

In [61]:
df1 = pd.read_csv(DATA_1_PATH)
df2 = pd.read_csv(DATA_2_PATH, header=1)
df3 = pd.read_csv(DATA_3_PATH)

## 2. Data Cleaning

Because the Google Form used for data collection changed a few times, there are 3 different csv files with varying columns that need to be combined into one csv file.

The output csv file should have the following columns:  
- timestamp (date)
- branch (string)
- zip (string)
- size (string)
- packs (int)

### 2a. File 1 - diapers.csv

Display summary information.

In [62]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 59425 entries, 0 to 59424
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Timestamp  55946 non-null  str
 1   BRANCH     55930 non-null  str
 2   ZIP CODE   55938 non-null  str
 3   SIZE       52387 non-null  str
 4   # PACKS    55793 non-null  float64
 5   SIZE.1     8397 non-null   str
 6   # PACKS.1  9265 non-null   float64
 7   SIZE.2     1785 non-null   str
 8   # PACKS.2  2873 non-null   float64
 9   TOTAL      59425 non-null  int64
 10  DATE       59425 non-null  str
 11  MONTH      55946 non-null  str
 12  YEAR       55946 non-null  str
 13  DAY        55946 non-null  str
 14  WEEKDAY    55946 non-null  str
dtypes: float64(3), int64(1), str(11)
memory usage: 6.8 MB

Select required columns.

In [63]:
df1_filtered: pd.DataFrame = df1.iloc[:, 0:9]
df1_filtered.head()

,Timestamp,BRANCH,ZIP CODE,SIZE,# PACKS,SIZE.1,# PACKS.1,SIZE.2,# PACKS.2
0,9/7/2021 0:00:00,GG,63011,1,3.0,NaN,NaN,NaN,NaN
1,9/7/2021 0:00:00,GG,63011,3T,2.0,NaN,NaN,NaN,NaN
2,9/14/2021 0:00:00,GG,63118,5,2.0,NaN,NaN,NaN,NaN
3,9/14/2021 0:00:00,GG,63118,6,2.0,NaN,NaN,NaN,NaN
4,9/14/2021 0:00:00,GG,63125,5,2.0,NaN,NaN,NaN,NaN

Stack rows.

In [64]:
def stack_rows(df_filtered: pd.DataFrame) -> list[list]:
    df_list = df_filtered.values.tolist()
    combined_data = []
    for record in df_list:
        for i in range(3, 9, 2):
            if record[i] != record[i] and record[i+1] != record[i+1]:
                continue
            row = [*record[0:3], *record[i:i+2]]
            combined_data.append(row)
    return combined_data

In [65]:
combined_data_1: list[list] = stack_rows(df1_filtered)

Create DataFrame.

In [66]:
def create_df(combined_data: list[list]) -> pd.DataFrame:
    columns: list = ["timestamp", "branch", "zip", "size", "packs"]
    df_final: pd.DataFrame = pd.DataFrame(combined_data, columns=columns)
    return df_final

In [67]:
df1_final: pd.DataFrame = create_df(combined_data_1)
df1_final.head()

           timestamp branch    zip size  packs
0   9/7/2021 0:00:00     GG  63011    1    3.0
1   9/7/2021 0:00:00     GG  63011   3T    2.0
2  9/14/2021 0:00:00     GG  63118    5    2.0
3  9/14/2021 0:00:00     GG  63118    6    2.0
4  9/14/2021 0:00:00     GG  63125    5    2.0

### 2b. File 2 - form.csv

Display summary information.

In [68]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 24514 entries, 0 to 24513
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Timestamp                                 24514 non-null  str
 1   BRANCH                                    24514 non-null  str
 2   ZIP CODE                                  24514 non-null  str
 3   What are you submitting stats for?        24514 non-null  str
 4   Size                                      19367 non-null  str
 5   Unnamed: 5                                19367 non-null  str
 6   Number of PACKS OF DIAPERS distributed    19367 non-null  float64
 7   Size.1                                    7267 non-null   str
 8   Unnamed: 8                                7267 non-null   str
 9   Number of PACKS OF DIAPERS distributed.1  7129 non-null   float64
 10  Size.2                                    1563 non-null   str
 11  Unnamed: 11                               1563 non-null   str
 12  Number of PACKS OF DIAPERS distributed.2  2328 non-null   float64
 13  Number of FLOW KITS distributed           4996 non-null   float64
 14  Number of REUSABLE FLOW KITS distributed  183 non-null    float64
dtypes: float64(5), str(10)
memory usage: 2.8 MB

In [69]:
df2.head(10)

,Timestamp,BRANCH,ZIP CODE,What are you submitting stats for?,Size,Unnamed: 5,Number of PACKS OF DIAPERS distributed,Size.1,Unnamed: 8,Number of PACKS OF DIAPERS distributed.1,Size.2,Unnamed: 11,Number of PACKS OF DIAPERS distributed.2,Number of FLOW KITS distributed,Number of REUSABLE FLOW KITS distributed
0,0/0/0000 00:00:00,----,-----,Flow Kits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1,0/0/0000 00:00:00,----,-----,Resuable Flow Kits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,0/0/0000 00:00:00,----,-----,Diapers,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/2/2024 9:29:02,LC,63137,Diapers,5,5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/2/2024 9:29:19,LC,63137,Resuable Flow Kits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
5,1/2/2024 9:38:49,LC,63136,Diapers,3,3,1.0,4,4,1.0,NaN,NaN,NaN,NaN,NaN
6,1/2/2024 9:48:33,WR,63123,Diapers,4T,4T,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1/2/2024 10:00:31,LC,62040,Diapers,4,4,1.0,4,4,1.0,NaN,NaN,NaN,NaN,NaN
8,1/2/2024 10:01:09,LC,62040,Resuable Flow Kits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9,1/2/2024 10:50:17,GG,63125,Diapers,2,2,1.0,2,2,1.0,3,3,1.0,NaN,NaN

Filter to select diaper stats only.

In [70]:
df2_diapers = df2[df2.iloc[:, 3] == "Diapers"]
df2_diapers.head()

,Timestamp,BRANCH,ZIP CODE,What are you submitting stats for?,Size,Unnamed: 5,Number of PACKS OF DIAPERS distributed,Size.1,Unnamed: 8,Number of PACKS OF DIAPERS distributed.1,Size.2,Unnamed: 11,Number of PACKS OF DIAPERS distributed.2,Number of FLOW KITS distributed,Number of REUSABLE FLOW KITS distributed
2,0/0/0000 00:00:00,----,-----,Diapers,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/2/2024 9:29:02,LC,63137,Diapers,5,5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1/2/2024 9:38:49,LC,63136,Diapers,3,3,1.0,4,4,1.0,NaN,NaN,NaN,NaN,NaN
6,1/2/2024 9:48:33,WR,63123,Diapers,4T,4T,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1/2/2024 10:00:31,LC,62040,Diapers,4,4,1.0,4,4,1.0,NaN,NaN,NaN,NaN,NaN

Select required columns.

In [71]:
df2_col_idx = [0,1,2,4,6,7,9,10,12]
df2_filtered = df2_diapers.iloc[1:,df2_col_idx]
df2_filtered.head()

,Timestamp,BRANCH,ZIP CODE,Size,Number of PACKS OF DIAPERS distributed,Size.1,Number of PACKS OF DIAPERS distributed.1,Size.2,Number of PACKS OF DIAPERS distributed.2
3,1/2/2024 9:29:02,LC,63137,5,1.0,NaN,NaN,NaN,NaN
5,1/2/2024 9:38:49,LC,63136,3,1.0,4,1.0,NaN,NaN
6,1/2/2024 9:48:33,WR,63123,4T,1.0,NaN,NaN,NaN,NaN
7,1/2/2024 10:00:31,LC,62040,4,1.0,4,1.0,NaN,NaN
9,1/2/2024 10:50:17,GG,63125,2,1.0,2,1.0,3,1.0

Stack rows.

In [72]:
combined_data_2: list[list] = stack_rows(df2_filtered)

Create DataFrame.

In [73]:
df2_final = create_df(combined_data_2)
df2_final.head()

           timestamp branch    zip size  packs
0   1/2/2024 9:29:02     LC  63137    5    1.0
1   1/2/2024 9:38:49     LC  63136    3    1.0
2   1/2/2024 9:38:49     LC  63136    4    1.0
3   1/2/2024 9:48:33     WR  63123   4T    1.0
4  1/2/2024 10:00:31     LC  62040    4    1.0

### 2c. File 3 - form2.csv

Display summary information.

In [74]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 8853 entries, 0 to 8852
Data columns (total 13 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   Timestamp                                                        8853 non-null   str
 1   BRANCH                                                           8827 non-null   str
 2   ZIP CODE                                                         8853 non-null   str
 3   Size                                                             7490 non-null   str
 4   Number of PACKS OF DIAPERS distributed                           7276 non-null   float64
 5   Size.1                                                           2208 non-null   str
 6   Number of PACKS OF DIAPERS distributed.1                         2144 non-null   float64
 7   Size.2                                                           436 non-null    str
 8   Number of PACKS OF DIAPERS distributed.2                         546 non-null    float64
 9   Number of FLOW KITS distributed                                  2730 non-null   float64
 10  Number of REUSABLE FLOW KITS distributed                         180 non-null    float64
 11  Do you want to record distribution statistics?                   2370 non-null   str
 12  Are you submitting statistics or enrolling a new diaper patron?  8853 non-null   str
dtypes: float64(5), str(8)
memory usage: 899.3 KB

In [75]:
df3.head()

,Timestamp,BRANCH,ZIP CODE,Size,Number of PACKS OF DIAPERS distributed,Size.1,Number of PACKS OF DIAPERS distributed.1,Size.2,Number of PACKS OF DIAPERS distributed.2,Number of FLOW KITS distributed,Number of REUSABLE FLOW KITS distributed,Do you want to record distribution statistics?,Are you submitting statistics or enrolling a new diaper patron?
0,9/9/2023 8:55:18,FV,12345,0,0.0,0,0.0,0,0.0,0.0,0.0,NaN,Diaper Distribution
1,10/17/2025 8:54:37,PV,63114,4,1.0,6,1.0,NaN,NaN,NaN,NaN,NaN,Statistics (Diapers + Flow Kits)
2,10/17/2025 8:59:27,FV,63137,5,2.0,4,1.0,NaN,NaN,1.0,NaN,NaN,Statistics (Diapers + Flow Kits)
3,10/17/2025 9:00:27,WR,63125,5,1.0,6,1.0,NaN,NaN,1.0,NaN,NaN,Statistics (Diapers + Flow Kits)
4,10/17/2025 9:00:27,FV,63031,3,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Statistics (Diapers + Flow Kits)

Select required columns.

In [76]:
df3_filtered = df3.iloc[1:, 0:9]
df3_filtered.head()

,Timestamp,BRANCH,ZIP CODE,Size,Number of PACKS OF DIAPERS distributed,Size.1,Number of PACKS OF DIAPERS distributed.1,Size.2,Number of PACKS OF DIAPERS distributed.2
1,10/17/2025 8:54:37,PV,63114,4,1.0,6,1.0,NaN,NaN
2,10/17/2025 8:59:27,FV,63137,5,2.0,4,1.0,NaN,NaN
3,10/17/2025 9:00:27,WR,63125,5,1.0,6,1.0,NaN,NaN
4,10/17/2025 9:00:27,FV,63031,3,1.0,NaN,NaN,NaN,NaN
5,10/17/2025 9:04:45,GG,63021,5,2.0,NaN,NaN,NaN,NaN

Stack rows.

In [77]:
combined_data_3: list[list] = stack_rows(df3_filtered)

Create DataFrame.

In [78]:
df3_final = create_df(combined_data_3)
df3_final.head()

            timestamp branch    zip size  packs
0  10/17/2025 8:54:37     PV  63114    4    1.0
1  10/17/2025 8:54:37     PV  63114    6    1.0
2  10/17/2025 8:59:27     FV  63137    5    2.0
3  10/17/2025 8:59:27     FV  63137    4    1.0
4  10/17/2025 9:00:27     WR  63125    5    1.0

### 2d. Combining DataFrames into One

Concatenating all three DataFrames.

In [79]:
df_combined = pd.concat([df1_final, df2_final, df3_final], axis=0, ignore_index=True)
df_combined.head()

           timestamp branch    zip size  packs
0   9/7/2021 0:00:00     GG  63011    1    3.0
1   9/7/2021 0:00:00     GG  63011   3T    2.0
2  9/14/2021 0:00:00     GG  63118    5    2.0
3  9/14/2021 0:00:00     GG  63118    6    2.0
4  9/14/2021 0:00:00     GG  63125    5    2.0

### 2e. Ensuring Validity of Entries

Display DataFrame information.

In [80]:
df_combined.isna().sum()

timestamp       1
branch         41
zip            10
size         6647
packs         825
dtype: int64

Check for na values in timestamp.

In [81]:
df_combined[df_combined["timestamp"].isna()]

      timestamp branch  zip size  packs
29164       NaN   ----  NaN    0    0.0

Drop row with na timestamp.

In [82]:
df_combined.drop([29164], inplace=True)

Reset index.

In [83]:
df_combined.reset_index(inplace=True, drop=True)

In [84]:
df_combined

                timestamp branch    zip size  packs
0        9/7/2021 0:00:00     GG  63011    1    3.0
1        9/7/2021 0:00:00     GG  63011   3T    2.0
2       9/14/2021 0:00:00     GG  63118    5    2.0
3       9/14/2021 0:00:00     GG  63118    6    2.0
4       9/14/2021 0:00:00     GG  63125    5    2.0
...                   ...    ...    ...  ...    ...
107513   7/3/2026 8:31:21     LC  63138    5    1.0
107514   7/3/2026 9:15:47     FV  63137   3T    1.0
107515   7/3/2026 9:15:47     FV  63137   2T    1.0
107516   7/3/2026 9:15:47     FV  63137   2T    1.0
107517   7/3/2026 9:32:40     WR  63123    4    1.0

[107518 rows x 5 columns]

In [85]:
df_combined.to_csv(OUTPUT_DATA_PATH, index=False)

## 3. Exploratory Analysis

In [86]:
df_combined.head()

           timestamp branch    zip size  packs
0   9/7/2021 0:00:00     GG  63011    1    3.0
1   9/7/2021 0:00:00     GG  63011   3T    2.0
2  9/14/2021 0:00:00     GG  63118    5    2.0
3  9/14/2021 0:00:00     GG  63118    6    2.0
4  9/14/2021 0:00:00     GG  63125    5    2.0

In [87]:
df_combined.tail()

               timestamp branch    zip size  packs
107513  7/3/2026 8:31:21     LC  63138    5    1.0
107514  7/3/2026 9:15:47     FV  63137   3T    1.0
107515  7/3/2026 9:15:47     FV  63137   2T    1.0
107516  7/3/2026 9:15:47     FV  63137   2T    1.0
107517  7/3/2026 9:32:40     WR  63123    4    1.0

### 3a. Diaper Size Analysis

Main Idea: Test if size ratios are consistent with Chi-Square

### 3b. Diaper Totals Analysis

Main idea: I suspect seasonality. Graph each month for each year on the same graph.

## 4. Predictive Modeling

### 4a. Estimating Diaper Totals

Main idea: Since there is a seasonal trand, use Holt-Winters Exponential Smoothing to predict totals.

### 4b. Estimating Diaper Size Totals

Main idea: number of size N diapers distributed in a month = size N proportion * estimated monthly total

## 5. Evaluating Models

### 5a. Diaper Totals Predictions

Main idea: Find the error in the model's predictions. Compare to 2026 data so far, or maybe validate on 2025 data.

### 5b. Diaper Size Totals Predictions

Main idea: Find the error in the model's predictions. Compare to 2026 data so far, or maybe validate on 2025 data.

## 6. Conclusions

Answer the following questions:
- What did I find out in exploratory analysis?
- How well did the models predict the test set?